		const beerData = {
		    'France': { beers: ['Kronenbourg', '1664', 'Pelforth'], anecdote: 'La France possède le plus grand nombre de brasseries en Europe, avec une explosion des micro-brasseries artisanales.' },
		    'Allemagne': { beers: ['Paulaner', 'Beck\'s', 'Warsteiner'], anecdote: 'En Bavière, la bière est officiellement considérée comme un aliment de base, au même titre que le pain.' },
		    'Belgique': { beers: ['Stella Artois', 'Leffe', 'Duvel'], anecdote: 'Les moines trappistes brassent encore selon des méthodes ancestrales au sein de leurs abbayes.' },
		    'États-Unis': { beers: ['Budweiser', 'Miller', 'Coors'], anecdote: 'Le mouvement des "Craft Beers" a révolutionné le marché mondial en réintroduisant des houblons très aromatiques.' },
		    'Mexique': { beers: ['Corona', 'Dos Equis', 'Modelo'], anecdote: 'Le Mexique est le premier exportateur mondial de bière, devançant largement les pays européens.' },
		    'Pays-Bas': { beers: ['Heineken', 'Grolsch', 'Amstel'], anecdote: 'Les Hollandais ont inventé les navires-brasseries au 17ème siècle pour fournir de la bière fraîche lors des longs voyages.' },
		    'Royaume-Uni': { beers: ['Bass Pale Ale','Carling', 'Newcastle Brown Ale'], anecdote: 'La tradition du "Real Ale" impose que la bière finisse sa fermentation naturellement dans le fût du pub.' },
		    'Irlande': { beers: ['Guinness', 'Murphy\'s', 'Smithwick\'s'], anecdote: 'La bière brune est si emblématique qu\'on la surnomme parfois "le pain liquide" ou "la substance noire".' },
		    'Italie': { beers: ['Peroni', 'Moretti', 'Nastro Azzurro'], anecdote: 'L\'Italie est pionnière dans le style "Italian Grape Ale", une bière brassée avec du moût de raisin.' },
		    'Espagne': { beers: ['Mahou', 'Estrella Damm', 'Cruzcampo'], anecdote: 'C\'est le pays d\'Europe où l\'on consomme le plus de bière sans alcool (près de 15% du marché).' },
		    'Japon': { beers: ['Asahi', 'Sapporo', 'Kirin'], anecdote: 'Au Japon, on trouve des distributeurs automatiques de bière dans les rues, accessibles avec une carte d\'identité.' },
		    'Chine': { beers: ['Tsingtao', 'Snow', 'Yanjing'], anecdote: 'La Chine est le plus grand producteur mondial de bière en volume total, devant les États-Unis.' },
		    'Brésil': { beers: ['Skol', 'Brahma', 'Antarctica'], anecdote: 'Les bouteilles de 600ml sont partagées dans des petits verres appelés "Americano" pour que la bière reste toujours glacée.' },
		    'Australie': { beers: ['Foster\'s', 'Victoria Bitter', 'Coopers'], anecdote: 'Les Australiens commandent leur bière par "Schooner" ou "Pot", des tailles de verres qui varient selon les États.' },
		    'Canada': { beers: ['Molson', 'Labatt', 'Moosehead'], anecdote: 'Le Québec possède une culture brassicole unique, très influencée par les méthodes artisanales belges.' },
		    'Tchéquie': { beers: ['Pilsner Urquell', 'Budvar', 'Staropramen'], anecdote: 'Les Tchèques consomment environ 140 litres de bière par an et par habitant, le record absolu.' },
		    'Danemark': { beers: ['Carlsberg', 'Tuborg', 'Mikkeller'], anecdote: 'Le Danemark a été l\'un des premiers pays au monde à instaurer un système de consigne pour les bouteilles.' },
		    'Portugal': { beers: ['Super Bock', 'Sagres'], anecdote: 'La consommation de bière dépasse celle du vin lors des fêtes populaires comme la Saint-Jean.' },
		    'Thaïlande': { beers: ['Singha', 'Chang', 'Leo'], anecdote: 'En raison de la chaleur, la bière y est quasi systématiquement servie avec des glaçons dans le verre.' },
		    'Turquie': { beers: ['Efes', 'Bomonti'], anecdote: 'Des preuves archéologiques montrent que l\'on brassait déjà des céréales en Anatolie il y a 10 000 ans.' },
		    'Grèce': { beers: ['Mythos', 'Fix', 'Alfa'], anecdote: 'La bière est la boisson préférée pour accompagner les "Mezzés" en bord de mer durant l\'été.' },
		    'Pologne': { beers: ['Tyskie', 'Żywiec', 'Lech'], anecdote: 'Une tradition polonaise consiste à boire la bière chaude avec du sirop de framboise ou des épices en hiver.' },
		    'Vietnam': { beers: ['Saigon Beer', '333', 'Hanoi Beer'], anecdote: 'Le "Bia Hoi" est une bière de rue brassée quotidiennement, sans conservateurs, et bue dans la journée.' },
		    'Philippines': { beers: ['San Miguel', 'Red Horse'], anecdote: 'La bière est souvent servie avec des "Pulutan", des amuse-gueules locaux comme le porc croustillant.' },
		    'Argentine': { beers: ['Quilmes', 'Isenbeck'], anecdote: 'Les Argentins consomment souvent la bière en grands formats de 1 litre à partager entre amis.' },
		    'Colombie': { beers: ['Club Colombia', 'Águila', 'Poker'], anecdote: 'Le "Tejo", sport national, se joue traditionnellement en buvant de la bière dans des jardins dédiés.' },
		    'Afrique du Sud': { beers: ['Castle Lager', 'Carling Black Label'], anecdote: 'La bière traditionnelle "Umqombothi", à base de sorgho et de maïs, est au cœur des cérémonies zouloues.' },
		    'Égypte': { beers: ['Stella (EGY)', 'Sakara'], anecdote: 'Dans l\'Antiquité égyptienne, la bière servait de monnaie pour payer les ouvriers des pyramides.' },
		    'Maroc': { beers: ['Casablanca', 'Flag Spéciale', 'Stork'], anecdote: 'Le pays produit des bières légères adaptées au climat méditerranéen depuis le début du 20ème siècle.' },
		    'Algérie': { beers: ['Tango', 'Sélecto (brasseries)'], anecdote: 'L\'Algérie a une longue tradition de culture du houblon et de l\'orge sur les hauts plateaux.' },
		    'Russie': { beers: ['Baltika', 'Zhigulevskoye'], anecdote: 'Ce n\'est qu\'en 2011 que la bière a été officiellement classée comme boisson alcoolisée (et non plus alimentaire).' },
		    'Ukraine': { beers: ['Obolon', 'Lvivske', 'Chernigivske'], anecdote: 'Lviv est considérée comme la capitale de la bière de l\'Est, avec des brasseries datant du Moyen-Âge.' },
		    'Inde': { beers: ['Kingfisher', 'Haywards 5000'], anecdote: 'L\'IPA (India Pale Ale) a été créée par les Anglais pour que la bière survive au voyage en bateau vers l\'Inde.' },
		    'Indonésie': { beers: ['Bintang', 'Anker'], anecdote: 'Malgré les restrictions culturelles, l\'île de Bali possède l\'une des plus fortes consommations de bière d\'Asie.' },
		    'Suisse': { beers: ['Feldschlösschen', 'Appenzeller', 'Calanda'], anecdote: 'La Suisse détient le record mondial du nombre de brasseries par habitant.' },
		    'Islande': { beers: ['Einstök', 'Gull', 'Viking'], anecdote: 'Le "Jour de la Bière" est fêté chaque 1er mars pour célébrer la fin de la prohibition en 1989.' },
		    'Tunisie': { beers: ['Celtia'], anecdote: 'La bière nationale est une véritable institution culturelle, servie dans des petites bouteilles en verre de 25cl.' },
		    'Bangladesh': { beers: ['Hunter'], anecdote: 'La vente d\'alcool est très réglementée, mais une bière locale au malt est autorisée sous certaines conditions.' },
		    'Kenya': { beers: ['Tusker', 'White Cap'], anecdote: 'L\'orge utilisée est cultivée directement sur les pentes des montagnes d\'Afrique de l\'Est.' },
		    'Nigeria': { beers: ['Star', 'Gulder'], anecdote: 'Le Nigeria est le deuxième plus gros marché de Guinness au monde, juste après le Royaume-Uni.' },
		    'Tanzanie': { beers: ['Safari', 'Kilimanjaro'], anecdote: 'Il est courant de boire la bière à température ambiante plutôt que glacée dans certaines régions.' },
		    'Ghana': { beers: ['Club Premium', 'Star'], anecdote: 'La bière de maïs et de millet est une alternative artisanale très populaire en zone rurale.' },
		    'Iran': { beers: ['Delster', 'Istak'], anecdote: 'Depuis 1979, on ne consomme que de la bière 0.0% alcool, souvent aromatisée aux fruits.' },
		    'Irak': { beers: ['Farida'], anecdote: 'Bagdad était autrefois réputée pour ses jardins de bière le long du fleuve Tigre.' },
		    'Émirats Arabes Unis': { beers: ['Craft by Side Hustle'], anecdote: 'La culture de la bière artisanale se développe via des brasseries qui ne produisent que sur place (sans mise en bouteille).' },
		    'Kazakhstan': { beers: ['Shymkent', 'Karaganda'], anecdote: 'La culture de la bière y est influencée par les traditions russes et la proximité de l\'Asie Centrale.' },
		    'Autriche': { beers: ['Stiegl', 'Ottakringer'], anecdote: 'Salzbourg est considérée comme la capitale autrichienne de la bière avec ses jardins ombragés par des marronniers.' },
		    'Suède': { beers: ['Pistonhead', 'Falcon'], anecdote: 'Le gouvernement gère un monopole (Systembolaget) pour la vente de bières de plus de 3.5%.' },
		    'Finlande': { beers: ['Karhu', 'Lapin Kulta'], anecdote: 'Les Finlandais apprécient la bière après une séance de sauna, c\'est une tradition quasi sacrée.' },
		    'Norvège': { beers: ['Ringnes', 'Frydenlund'], anecdote: 'Les prix de la bière en Norvège sont parmi les plus élevés au monde en raison des taxes sur l\'alcool.' },
		    'Israël': { beers: ['Goldstar', 'Maccabee'], anecdote: 'Des chercheurs israéliens ont récemment recréé une bière en utilisant des levures vieilles de 5 000 ans.' },
		    'Liban': { beers: ['Almaza', 'Beirut Beer'], anecdote: 'Le Liban possède les plus anciennes brasseries modernes du monde arabe.' },
		    'Corée du Nord': { beers: ['Taedonggang'], anecdote: 'Le pays organise parfois son propre festival de la bière à Pyongyang, inspiré de l\'Oktoberfest.' },
		    'Pakistan': { beers: ['Murree Beer'], anecdote: 'L\'unique brasserie du pays existe depuis 1860 et produit légalement pour les minorités et les étrangers.' },
		    'Uruguay': { beers: ['Patricia', 'Pilsen'], anecdote: 'La bière y est souvent consommée dans des "Chop", des chopes en céramique typiques.' }
		};
		
window.beerData = beerData;
		